name: test slack notifications

on:
  workflow_dispatch:

jobs:
  call-slack-notif:
    uses: cenevan/gha-workflows/.github/workflows/reusable-slack-notifs.yml@main
    with:
      short-desc: 'Core SDK v1.0.demo'
      title: 'Package Published'
      img-url: 'https://i.imgur.com/eqfFZRb.jpeg'
      img-alt-text: 'Test alt text'
    secrets:
      channel-name: ${{ secrets.SLACK_CHANNEL_ID_STORY_57BLOCKS }}
      slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
